"use client"
// Auto-generated by `npx boneyard-js build` — do not edit
import { registerBones } from 'boneyard-js'
import { configureBoneyard } from 'boneyard-js/react'

import _mission_control from './mission-control.bones.json'
import _scope_map from './scope-map.bones.json'

configureBoneyard({"color":"#e4e4e7","darkColor":"#27272a","animate":"pulse"})

registerBones({
  "mission-control": _mission_control,
  "scope-map": _scope_map,
})
